import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NavBar from "./_components/NavBar";
import QueryProvider from "./_components/QueryProvider";
import styles from "./layout.module.css";
import "./globals.css";
import { SLIDES_MAP } from "./_data/tenses";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <QueryProvider>
          <div className={styles.shell}>
            <NavBar items={SLIDES_MAP} />
            <main className={styles.main}>{children}</main>
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
